# Generated by Django 5.0.6 on 2024-05-31 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animeName', models.CharField(max_length=255, verbose_name='Anime name')),
                ('cover', models.CharField(max_length=500, verbose_name='Link to cover')),
                ('poster', models.CharField(max_length=500, verbose_name='Link to poster')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('animeLink', models.CharField(max_length=500, verbose_name='YouTube')),
                ('description', models.TextField(verbose_name='Description')),
                ('inTrend', models.BooleanField(blank=True, default=False, null=True, verbose_name='Intrend')),
                ('bestSeason', models.BooleanField(default=False, verbose_name='Best of the season')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatName', models.CharField(max_length=255, verbose_name='Format name')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=255, verbose_name='Genre name')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearValue', models.IntegerField(unique=True, verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('episode_number', models.IntegerField()),
                ('video_link', models.CharField(max_length=500)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime_app.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anime_app.format', verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.genre', verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_app.year', verbose_name='Year'),
        ),
    ]
