# Generated by Django 5.0.6 on 2024-05-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='bestSeason',
            field=models.BooleanField(default=False, verbose_name='Best of the season'),
        ),
        migrations.AddField(
            model_name='anime',
            name='inTrend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Intrend'),
        ),
    ]
