# Generated by Django 5.0.6 on 2024-06-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0002_anime_bestseason_anime_intrend'),
        ('anime_app', '0003_alter_favorite_unique_together_alter_favorite_anime'),
    ]

    operations = [
    ]
